package com.iwrite.audit.entity;

public enum AuditAction {
    BOOK_CREATED,
    BOOK_UPDATED,
    BOOK_DELETED,
    PERSONAL_WRITING_GOAL_UPDATED,
    SCENE_CREATED,
    SCENE_UPDATED,
    SCENE_CONTENT_UPDATED,
    SCENE_PLANNING_UPDATED,
    SCENE_DELETED,
    COLLABORATOR_ADDED,
    COLLABORATOR_REMOVED,
    SCENE_VERSION_RESTORED,
    OPENAI_SCENE_ANALYSIS,
    MCP_BOOKS_LISTED,
    MCP_BOOK_OUTLINE_VIEWED,
    MCP_SCENE_ANALYZED
}
